#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class TextBox;
                ref class CheckBox;
                ref class TextBlock;
                ref class ComboBox;
                ref class Canvas;
            }
        }
    }
}

namespace TDEAnalysis
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::TextBox^ fileName;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ multiple;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ text;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ calcType;
        private: ::Windows::UI::Xaml::Controls::TextBox^ calcSize;
        private: ::Windows::UI::Xaml::Controls::TextBox^ calcMin;
        private: ::Windows::UI::Xaml::Controls::TextBox^ calcMax;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ ref;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ sig;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ rt;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ clr;
        private: ::Windows::UI::Xaml::Controls::TextBox^ delay1;
        private: ::Windows::UI::Xaml::Controls::TextBox^ delay2;
        private: ::Windows::UI::Xaml::Controls::TextBox^ delay3;
        private: ::Windows::UI::Xaml::Controls::Canvas^ canvas1;
        private: ::Windows::UI::Xaml::Controls::Canvas^ canvas2;
    };
}

